server:
  port: 8081

com.renthouse.enviroment:
  telegram:
    botUserName:
    botToken:

com.google.calendar:
  clientId:
  projectId:
  clientSecret:
  localhost:
  redirectPort:
  refreshToken:
  calendarId: